### ISSUE TITLE
Invalid path is generated when title contains certain character

### ISSUE THREAD

**Issue by h0rn3z0r** [taburineagle/MPC-HC-Looper#7]
Greetings, it seems like the vertical slash ( | ) in media file's title messes everything up. This leads not only to a wrong path in the .looper file, but also freezes the player.

**Comment by taburineagle** [comment]
Hello!  This does make sense, as the "|" character is the delimiter for .looper files (.looper files are basically text files with the vertical slash character delimiting the event name, IN and OUT point, and filepath to that event):

1 - Event 1 Name|IN Point|OUT Point|File Path
2 - Event 2 Name|IN Point|OUT Point|File Path, etc.

So if you have an event that uses that character in the event's name, it will feed the wrong information to Looper when the file loads, as it splits that event's information prematurely (making MPC-HC look for a file using an OUT point, like "12:35" instead of a correct path) - I am slightly confused though, do you have events with that character in the event's _name_ or the media file's path itself, because I can't actually create a media file with "|" in the path (Windows doesn't allow filenames or paths using the "|" character)

**Comment by h0rn3z0r** [comment]
@taburineagle, I agree, by "media file's title" I meant exactly this entry in its metadata:

![image](https://user-images.githubusercontent.com/8987403/111141794-ff4fb580-8594-11eb-941a-11df84117060.png)

Not sure how the looper uses it, but I have plenty of such files and you won't be able to use them until the metadata is cleared.

**Comment by taburineagle** [comment]
Ahhh, I _think_ I know where it's getting that - when MPC-HC sends the "now playing" info back to Looper, it also uses a "|" delimiter, but it returns the media file's "title" along with the duration, language, path, etc., so Looper is getting its information from the wrong fields in that case.  Let me check into this one...
